// Day7/Practice/Practice1/Source/CtoP_Ang/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',

})
export class AppComponent {
  title = 'CtoP_Ang';
  name: string ="";
  handleChange(name:string){
    this.name = name;
  }
}

<app-profile (keyupChange)="handleChange($event)"></app-profile>
<h1>Hello! {{name}}</h1>

// Day7/Practice/Practice2/Source/ctop_react/src/App.js
import Profile from "./components/Profile";
import { useState } from "react";

const App = () => {
  const [Name, setName] = useState("");

  const handleChange = (item) => {
    setName(item);
  };
  return (
    <div>
      <h1>Hello, {Name}</h1>
      <Profile keyupChange={handleChange} />
    </div>
  );
};

export default App;
