// Day3/Practice/Practice3/Source/calc_react/src/App.js

import './App.css';
import { useState } from 'react';
import Calc from './Calc';

function App() {
  let [num1,setNum1] = useState(0);
  let [num2,setNum2] = useState(0);
  let [opr, setOpr] = useState('');
  return (
    <div className="App">
      <div class="child">
      <div>
        <label for="num1">Enter Num1: </label>
        <input type="number" name="num1" id="num1" onChange={(e)=>setNum1(e.target.value)} />
      </div>
      <div>
        <label for="num2">Enter Num2: </label>
        <input type="number" name="num2" id="num2"  onChange={(e)=>setNum2(e.target.value)}/>
      </div>
      <div>
        <select onChange={(e)=>setOpr(e.target.value)}>
          <option value="+">+</option>
          <option value="-">-</option>
          <option value="*">*</option>
          <option value="/">/</option>
        </select>
      </div>
      <Calc num1={num1} num2={num2} opr={opr}/>
      </div>

    </div>
  );
}

export default App;

// Day3/Practice/Practice1/Source/Calc_Ang/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'Calc_Ang';
  num1: number = 0;
  num2: number = 0;
  operation: string = '+';
}

<div class="main-div">
  <div class="child">
    <div>
      <label for="num1">Enter Num1: </label>
      <input type="number" name="num1" id="num1" [(ngModel)]="num1" />
    </div>
    <div>
      <label for="num2">Enter Num2: </label>
      <input type="number" name="num2" id="num2" [(ngModel)]="num2" />
    </div>
    <div>
      <select id="operation" name="operation" [(ngModel)]="operation">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
      </select>
    </div>
    <app-calc [num1]="num1" [num2]="num2" [operation]="operation"></app-calc>
  </div>
</div>
