// Day2/Practice/Practice1/Source/AtoZ_Ang/src/app/alphabet/alphabet.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-alphabet',
  templateUrl: './alphabet.component.html',

})
export class AlphabetComponent{
  alphabets: string[] = [];
  constructor() {
    for (let i = 65; i < 91; i++) {
      this.alphabets.push(String.fromCharCode(i));
    }
  }

}

<style>
  .alphabets > li {
    color: red;
    list-style-type: none;
  }
</style>
<ul class="alphabets">
  <li *ngFor="let alphabet of alphabets">
    {{ alphabet }}
  </li>
</ul>

// Day2/Practice/Practice2/Source/AtoZ_Vue/src/components/Alphabet.vue
<script>
const genAlphabets = () => {
  const alphabets = [];
  for (let i = 65; i < 91; i++) {
    alphabets.push(String.fromCharCode(i));
  }
  return alphabets;
};
export default {
  data() {
    return {
      alphabets: genAlphabets(),
    };
  },
};
</script>

<template>
  <ul>
    <li v-for="alphabet of alphabets">
      {{ alphabet }}
    </li>
  </ul>
</template>
