// Day11/Practice/Practice1/Source/Routing_Ang/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'Routing_Ang';
}

<div>
  <h1 class="text-center text-secondary mt-4">Angular Routing</h1>
</div>

<div class="container mt-3 p-3 bg-primary">
  <a routerLink="/home" class="text-white mx-5 fs-3">Home</a>
  <a routerLink="/about" class="text-white mx-5 fs-3">About</a>
  <a routerLink="/contact" class="text-white mx-5 fs-3">Contact</a>
</div>

<router-outlet></router-outlet>

// Day13/Practice/Practice3/Source/NestedRoutes_Vue/src/App.vue
<script>
import { RouterLink, RouterView } from "vue-router";
export default {
  components: {
    RouterLink,
    RouterView,
  },
};
</script>

<template>
  <div class="container mt-5 text-center">
    <h1 class="text-success">Nested Routing In VUE</h1>
    <RouterLink to="/about"
      ><button class="btn btn-primary">ABOUT ME</button></RouterLink
    >
  </div>
  <RouterView />
</template>
