// Day5/Practice/Practice2/Source/even1to100_react/src/Even.js
import "./App.css";
const Even = () => {
  let arr = [];
  for (let i = 1; i <= 100; i++) {
    if (i % 2 === 0) {
      arr.push(i);
    }
  }
  return arr.map((value) => {
    return (
      <div className="main-div">
        <div className="even-item">{value}</div>
      </div>
    );
  });
};

export default Even;

// Day4/Practice/Practice3/Source/Even1to100_Ang/src/app/even/even.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-even',
  templateUrl: './even.component.html',
  styleUrls: ['./even.component.css'],
})
export class EvenComponent {
  evenNumbers: number[] = [];
  item: any;
  constructor() {
    for (let i = 1; i <= 100; i++) {
      if (i % 2 == 0) {
        this.evenNumbers.push(i);
      }
    }
  }
}

<h1>Even Numbers</h1>
<div class="main-div">
  <div *ngFor="let item of evenNumbers" class="even-item">
    {{ item }}
  </div>
</div>
