// Day3/Practice/Practice1/Source/Calc_Ang/src/app/calc/calc.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-calc',
  templateUrl: './calc.component.html',
  styleUrls: ['./calc.component.css'],
})
export class CalcComponent {
  @Input() num1: number = 0;
  @Input() num2: number = 0;
  @Input() operation: string = '+';
  result: number| string= 0;

  computation() {
    const num1 = this.num1,
      num2 = this.num2;
    switch (this.operation) {
      case '+':
        this.result = num1 + num2;
        break;
      case '-':
        this.result = num1 - num2;
        break;
      case '*':
        this.result = num1 * num2;
        break;
      case '/':
        this.result = num1 / num2;
        break;
      default:
        this.result = 'Invalid';
        break;
    }
  }
}


<div>
    <button (click)="computation()">Calculate</button>
    <h1>Result is {{result}}</h1>
  </div>

// Day3/Practice/Practice2/Source/Calc_Vue/src/components/Calc.vue
<script>
export default {
  props: {
    form: {
      num1: Number,
      num2: Number,
      operator: String,
    },
  },
  data() {
    return {
      result: "",
    };
  },
  methods: {
    computation() {
      let result;
      const num1 = this.form.num1,
        num2 = this.form.num2;
      switch (this.form.operation) {
        case "+":
          result = num1 + num2;
          break;
        case "-":
          result = num1 - num2;
          break;
        case "*":
          result = num1 * num2;
          break;
        case "/":
          result = num1 / num2;
          break;
      }
      this.result = result;
    },
  },
};
</script>

<template>
  <button v-on:click="computation()">Calculate</button>
  <h1 style="text-align: center; font-size: 3rem">Result is {{ result }}</h1>
</template>

<style scoped>
button {
  padding: 1rem;
  font-size: 1.5rem;
  color: blue;
  border-radius: 10px;
}
</style>
