// Day6/Assignments/Assignment3/Source/ProductList_vue/src/App.vue
<script>
import * as bootstrap from "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import ProductList from "./components/ProductList.vue";
export default {
  components: {
    ProductList,
  },
};
</script>

<template>
  <div>
    <h1 class="text-center mt-5">Product Listing</h1>
    <ProductList />
  </div>
</template>

// Day3/Assignments/Assignment2/Source/arearect_react/src/App.js
import bootstrap from "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";
import Login from "./components/Login";
import Signup from "./components/Signup";
import Rectangle from "./components/Rectangle";

function App() {
  return (
    <>
      <div className="container mt-5">
        <Login />
      </div>
      <div className="container mt-5">
        <Signup />
      </div>
      <div className="container mt-5">
        <Rectangle />
      </div>
    </>
  );
}

export default App;
