// Day3/Assignments/Assignment3/Source/AreaRect_Vue/src/App.vue
<script>
import * as bootstrap from "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import Rectangle from "./components/Rectangle.vue";
import Login from "./components/Login.vue";
import Signup from "./components/Signup.vue";
export default {
  components: {
    Rectangle,
    Login,
    Signup
  },
};
</script>

<template>
 <div class="container mt-5">
        <Login />
      </div>
      <div class="container mt-5">
        <Signup />
      </div>
      <div class="container mt-5">
        <Rectangle />
      </div>
</template>

// Day3/Assignments/Assignment2/Source/arearect_react/src/App.js
import bootstrap from "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";
import Login from "./components/Login";
import Signup from "./components/Signup";
import Rectangle from "./components/Rectangle";

function App() {
  return (
    <>
      <div className="container mt-5">
        <Login />
      </div>
      <div className="container mt-5">
        <Signup />
      </div>
      <div className="container mt-5">
        <Rectangle />
      </div>
    </>
  );
}

export default App;
