// Day3/Assignments/Assignment1/Source/AreaRect_Ang/src/app/signup/signup.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent {
  name: string = '';
  pan: string = '';
  address: string = '';
  description: string = '';

  signUp() {
    this.description = `name:${this.name}`;
  }
}



<div>
    <h1>Sign Up Component</h1>
    <form>
        <div class="d-flex flex-column gap-4">
        <div class="form-group">
            <input type="text" class="form-control" id="name" name="name" [(ngModel)]="name" placeholder="Enter Name">
        </div>
        
        <div class="form-group">
            <input type="text" class="form-control" id="address" name="address" [(ngModel)]="address" placeholder="Enter Address.">
        </div>  
        <div class="form-group">
            <input type="text" class="form-control" id="pan" name="pan" [(ngModel)]="pan" placeholder="Enter PAN Number">
        </div>  
        <button type="button" class="btn btn-primary" (click)="signUp()">Sign Up</button>
    </div>
    </form>
</div>

// Day3/Assignments/Assignment3/Source/AreaRect_Vue/src/components/Signup.vue
<script>
export default {
  data() {
    return {
      name: "",
      pan: "",
      address: "",

      description: "",
    };
  },

  methods: {
    signup() {
      if (this.name !== "" && this.pan !== "" && this.address !== "") {
        this.description = `Name: ${this.name} Address: ${this.address} has PAN No: ${this.pan}`;
      }
    },
  },
};
</script>
<template>
  <input
    type="text"
    name="name"
    id="name"
    placeholder="Enter Name"
    v-model="name"
  />

  <input
    type="text"
    name="address"
    id="address"
    placeholder="Enter Address"
    v-model="address"
  />

  <input
    type="text"
    name="pan"
    id="pan"
    placeholder="Enter PAN Number"
    v-model="pan"
  />

  <button @click="signup" class="btn btn-success">Submit</button>
  <h1>{{ description }}</h1>
</template>
