// Day3/Practice/Practice3/Source/calc_react/src/Calc.js
import React, { useState } from "react";

const Calc = (props) => {
  let [result, setResult] = useState(0);
  const handleComputation = (e) => {
    const num1 = props.num1,
      num2 = props.num2;
    switch (props.opr) {
      case "+":
        setResult(parseInt(num1) + parseInt(num2));
        break;
      case "-":
        setResult(parseInt(num1) - parseInt(num2));
        break;
      case "*":
        setResult(parseInt(num1) * parseInt(num2));
        break;
      case "/":
        setResult(parseInt(num1) / parseInt(num2));
        break;
      default:
        setResult("Invalid");
        break;
    }
  };
  return (
    <div>
      <button onClick={handleComputation}>Calculate</button>
      <p class="result">Result is {result}</p>
    </div>
  );
};

export default Calc;

// Day3/Practice/Practice1/Source/Calc_Ang/src/app/calc/calc.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-calc',
  templateUrl: './calc.component.html',
  styleUrls: ['./calc.component.css'],
})
export class CalcComponent {
  @Input() num1: number = 0;
  @Input() num2: number = 0;
  @Input() operation: string = '+';
  result: number| string= 0;

  computation() {
    const num1 = this.num1,
      num2 = this.num2;
    switch (this.operation) {
      case '+':
        this.result = num1 + num2;
        break;
      case '-':
        this.result = num1 - num2;
        break;
      case '*':
        this.result = num1 * num2;
        break;
      case '/':
        this.result = num1 / num2;
        break;
      default:
        this.result = 'Invalid';
        break;
    }
  }
}


<div>
    <button (click)="computation()">Calculate</button>
    <h1>Result is {{result}}</h1>
  </div>
