// Day6/Practice/Practice2/Source/ptoc_react/src/App.js
import { useState } from "react";

import "bootstrap/dist/css/bootstrap.min.css";
import Display from "./components/Display";

function App() {
  const [name, setName] = useState("");
  const handleNameState = (e) => {
    setName(e.target.value);
  };

  return (
    <div class="container d-flex flex-column gap-3 align-items-center mt-5">
      <Display name={name} />
      <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name"  onChange={handleNameState} />
    </div>
  );
}

export default App;

// Day6/Practice/Practice3/Source/PtoC_Vue/src/App.vue
<script setup>
import * as bootstrap from "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import Display from "./components/Display.vue";
</script>

<script>
export default {
  data() {
    return {
      name: "",
    };
  },
};
</script>

<template>
  <header>
    <div class="container gap-3 mt-5 d-flex flex-column align-items-center">
      <Display v-bind:name="name" />
      <input type="text" v-model="name" />
    </div>
  </header>
</template>
