// Day3/Assignments/Assignment3/Source/AreaRect_Vue/src/components/Login.vue
<script>
export default {
  data(){
    return {
      username: "",
      password: "",
      loggedin:false
    };
  },

  methods: {
    login() {
      if (this.username === "admin" && this.password === "admin") {
       this.loggedin=true
      }
    },
  },
};
</script>
<template>
 
  <input
    type="text"
    name="username"
    id="username"
    placeholder="Username"
    v-model="username"
  />
  <input
    type="password"
    name="password"
    id="password"
    placeholder="*******"
    v-model="password"
  />
  <input type="submit" value="Login" @click="login" class="btn btn-primary"/>
  <h1 v-if="loggedin">Login Successful</h1>
</template>

// Day3/Assignments/Assignment2/Source/arearect_react/src/components/Login.js
import { useState } from "react";

const Login = () => {
  const [user, setUser] = useState({ username: "", password: "" });

  const login = (e) => {
    e.preventDefault();
    if (user.username !== "admin" || user.password !== "admin") {
      alert("Wrong Credentials");
    }else{
      alert("Login Successfull")
    }
  };

  return (
    <>
      <input
        type="text"
        name="username"
        value={user.username}
        onChange={(e) => {
          setUser({ ...user, username: e.target.value });
        }}
        placeholder="Enter Username"
      />
       <input
        type="password"
        name="password"
        value={user.password}
        onChange={(e) => {
          setUser({ ...user, password: e.target.value });
        }}
        placeholder="Enter Password"
      />
      <input type="submit" value="Login" onClick={login}/>
    </>
  );
};

export default Login ;
