// Day3/Assignments/Assignment1/Source/AreaRect_Ang/src/app/rectangle/rectangle.component.ts
import { Component,  } from '@angular/core';

@Component({
  selector: 'app-rectangle',
  templateUrl: './rectangle.component.html',
  styleUrls: ['./rectangle.component.css']
})
export class RectangleComponent{
  height:string=''
  width:string=''
  area:number=0


  computeArea(){
    this.area= parseInt(this.height) * parseInt(this.width)
  }
  

}



<div>
    <h1>Rectangle Component</h1>
    <form  action="">
        <div class="d-flex flex-column gap-4">
        <div class="form-group">
            <label for="height">Enter Height:</label>
            <input class="form-control" type="number" id="height" name="height" placeholder="Unit: (cm)" [(ngModel)]="height">
        </div>
        <div class="form-group">
            <label for="width">Enter Width:</label>
            <input class="form-control" type="number" id="width" name="width" placeholder="Unit: (cm)" [(ngModel)]="width" >
        </div>
        <button type="button" class="btn btn-warning" (click)="computeArea()">Calculate Area</button>
    </div>
    </form>

    <div>
        <h1>Area is {{area}}</h1>
    </div>
</div>

// Day3/Assignments/Assignment2/Source/arearect_react/src/components/Rectangle.js
import { useState } from "react";

const Rectangle = () => {
  const [rectangle, setRectangle] = useState({ length: 0, breadth: 0 ,area:0 });
  function ComputeArea() {
     
    setRectangle({ ...rectangle, area: rectangle.length * rectangle.breadth })
    
  }

  return (
    <>
    <label htmlFor="length">Enter Length: </label>
      <input
        type="number"
        name="length"
        id="length"
        
        placeholder="Unit:(cm)"
        onChange={(e) => {
          setRectangle({ ...rectangle, length: parseInt(e.target.value) });
        }}
      />

      <label htmlFor="breadth">Enter Breadth: </label>
      <input
        type="number"
        name="breadth"
        id="breadth"
   
        placeholder="Unit:(cm)"
        onChange={(e) => {
          setRectangle({ ...rectangle, breadth: parseInt(e.target.value) });
        }}
      />
      <button
              
        onClick={ComputeArea}
      >Calculate Area</button>
      {rectangle.area}
    </>
  );
};

export default Rectangle;
