// Day3/Assignments/Assignment3/Source/AreaRect_Vue/src/components/Rectangle.vue
<script>
export default {
  data() {
    return {
      length: Number,
      breadth: Number,
      area: 0,
    };
  },
  methods: {
    computeArea() {
      this.area = this.length * this.breadth;
      console.log(area);
    },
  },
};
</script>

<template>
  <div class="main-div">
    <div class="child">
      <div>
        <label for="length">Enter Length: </label>
        <input
          type="number"
          name="length"
          id="length"
          placeholder="Unit:(cm)"
          v-model="length"
        />
      </div>
      <div>
        <label for="breadth">Enter Breadth: </label>
        <input
          type="number"
          name="breadth"
          id="breadth"
          placeholder="Unit:(cm)"
          v-model="breadth"
        />
      </div>
    </div>
  </div>

  <button v-on:click="computeArea" class="btn btn-danger">Calculate Area</button>
  <h1 style="text-align: center; font-size: 3rem">Area = {{ area }}</h1>
</template>

// Day3/Assignments/Assignment2/Source/arearect_react/src/components/Rectangle.js
import { useState } from "react";

const Rectangle = () => {
  const [rectangle, setRectangle] = useState({ length: 0, breadth: 0 ,area:0 });
  function ComputeArea() {
     
    setRectangle({ ...rectangle, area: rectangle.length * rectangle.breadth })
    
  }

  return (
    <>
    <label htmlFor="length">Enter Length: </label>
      <input
        type="number"
        name="length"
        id="length"
        
        placeholder="Unit:(cm)"
        onChange={(e) => {
          setRectangle({ ...rectangle, length: parseInt(e.target.value) });
        }}
      />

      <label htmlFor="breadth">Enter Breadth: </label>
      <input
        type="number"
        name="breadth"
        id="breadth"
   
        placeholder="Unit:(cm)"
        onChange={(e) => {
          setRectangle({ ...rectangle, breadth: parseInt(e.target.value) });
        }}
      />
      <button
              
        onClick={ComputeArea}
      >Calculate Area</button>
      {rectangle.area}
    </>
  );
};

export default Rectangle;
