// Day3/Assignments/Assignment3/Source/AreaRect_Vue/src/components/Signup.vue
<script>
export default {
  data() {
    return {
      name: "",
      pan: "",
      address: "",

      description: "",
    };
  },

  methods: {
    signup() {
      if (this.name !== "" && this.pan !== "" && this.address !== "") {
        this.description = `Name: ${this.name} Address: ${this.address} has PAN No: ${this.pan}`;
      }
    },
  },
};
</script>
<template>
  <input
    type="text"
    name="name"
    id="name"
    placeholder="Enter Name"
    v-model="name"
  />

  <input
    type="text"
    name="address"
    id="address"
    placeholder="Enter Address"
    v-model="address"
  />

  <input
    type="text"
    name="pan"
    id="pan"
    placeholder="Enter PAN Number"
    v-model="pan"
  />

  <button @click="signup" class="btn btn-success">Submit</button>
  <h1>{{ description }}</h1>
</template>

// Day3/Assignments/Assignment2/Source/arearect_react/src/components/Signup.js
import { useState } from "react";

const Signup = () => {
  const [register, setRegister] = useState({ name: "", address: "", pan: "" });
  const [description, setDescription] = useState("");

  function detail() {
    setDescription(
      `Name: ${register.name} lives in ${register.address} and PAN NO is ${register.pan} `
    );
  }

  return (
    <>
      <input
        type="text"
        name="name"
        value={register.username}
        onChange={(e) => {
          setRegister({ ...register, name: e.target.value });
        }}
        placeholder="Enter Username"
      />
      <input
        type="text"
        name="address"
        value={register.password}
        onChange={(e) => {
          setRegister({ ...register, address: e.target.value });
        }}
        placeholder="Enter Address"
      />
      <input
        type="text"
        name="pan"
        value={register.password}
        onChange={(e) => {
          setRegister({ ...register, pan: e.target.value });
        }}
        placeholder="Enter PAN"
      />
      <input type="submit" value="Signup" onClick={detail} />
      {description}
    </>
  );
};

export default Signup;
