// Day4/Practice/Practice1/Source/Greater_Ang/src/app/greater/greater.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-greater',
  templateUrl: './greater.component.html',
  styleUrls: ['./greater.component.css'],
})
export class GreaterComponent {
  @Input() num1: number = 0;
  @Input() num2: number = 0;
}

<div *ngIf="num1 > num2; else elseIfBlock">{{ num1 }} is Greater</div>
<ng-template #elseIfBlock>
  <div *ngIf="num2 > num1; else elseBlock">{{ num2 }} is Greater</div>
  <ng-template #elseBlock>
    <div>Both are Equal</div></ng-template>
</ng-template>

// Day5/Practice/Practice1/Source/greater_react/src/Greater.js
import React from "react";
import "./App.css";

const Greater = (props) => {
  const num1 = props.num1,
    num2 = props.num2;
  return (
    <div>
      {num1 > num2 ? (
        <h1>{num1} is Greater </h1>
      ) : (
        <>
          {num2 > num1 ? <h1>{num2} is Greater </h1> : <h1>Both are Equal</h1>}
        </>
      )}
    </div>
  );
};

export default Greater;
