// Day3/Assignments/Assignment2/Source/arearect_react/src/components/Login.js
import { useState } from "react";

const Login = () => {
  const [user, setUser] = useState({ username: "", password: "" });

  const login = (e) => {
    e.preventDefault();
    if (user.username !== "admin" || user.password !== "admin") {
      alert("Wrong Credentials");
    }else{
      alert("Login Successfull")
    }
  };

  return (
    <>
      <input
        type="text"
        name="username"
        value={user.username}
        onChange={(e) => {
          setUser({ ...user, username: e.target.value });
        }}
        placeholder="Enter Username"
      />
       <input
        type="password"
        name="password"
        value={user.password}
        onChange={(e) => {
          setUser({ ...user, password: e.target.value });
        }}
        placeholder="Enter Password"
      />
      <input type="submit" value="Login" onClick={login}/>
    </>
  );
};

export default Login ;

// Day3/Assignments/Assignment1/Source/AreaRect_Ang/src/app/login/login.component.ts
import { Component} from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username:string=''
  password:string=''
  loggedin:boolean=false

  login(){
    if(this.username==="admin" && this.password==="admin"){
      this.loggedin=true
    }else{
      alert("Wrong Credentials")
    }
  }
}



<div class="d-flex flex-column gap-3">
  <h1>Login Component</h1>

  <div>
    <div *ngIf="loggedin; then thenBlock; else elseBlock"></div>
    <ng-template #thenBlock
      >{{ username }} is Successfully Logged In</ng-template
    >
    <ng-template #elseBlock
      ><form>
        <div class="d-flex flex-column gap-4">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              type="text"
              class="form-control"
              id="username"
              name="username"
              [(ngModel)]="username"
              placeholder="Enter Username."
            />
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input
              type="password"
              class="form-control"
              id="password"
              name="password"
              [(ngModel)]="password"
              placeholder="Enter Password."
            />
          </div>
          <button type="button" class="btn btn-danger" (click)="login()">
            Login
          </button>
        </div>
      </form></ng-template
    >
  </div>
</div>
